version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
    networks:
      - todo-network
    image: thanhhien52/todo-frontend:latest

  backend:
    build: ./backend
    ports:
      - '3030:3030'
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
    networks:
      - todo-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    image: thanhhien52/todo-backend:latest

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mongo-data:
