name: CI/CD Docker Compose

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Đăng nhập Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build các image Docker Compose
      - name: Build Docker images
        run: docker compose build

      # Push image lên Docker Hub
      - name: Push Docker images
        run: docker compose push
